### ISSUE TITLE
Editor and images in Chrome on Windows

### ISSUE THREAD

**Issue by gcielniak** [marc-hanheide/QuickVote#14]
Have problem copy&pasting in this configuration. Adding a new question and answers is fine until I want to paste the image. When I access the edit form, everything hangs without even trying to paste. No problem on Mac and Chrome. However when the default question in the viewer is set to one without the image, everything works fine. Can demonstrate at some point when you are around.

**Comment by marc-hanheide** [comment]
Yeah, demonstration would help. I don't fully understand...

**Comment by marc-hanheide** [comment]
We identified this is mostly a problem with copy/paste being slow on Windows. The problem is that the pasting works with a [data-uri](https://en.wikipedia.org/wiki/Data_URI_scheme) and apparently that's not really of good performance. Indeed, the way images are pasted should be improved (not a text field), but this is an enhancement, see #16. So this bug, isn't one...
